name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 
        run: mkdir -p tests/build

      - name: 
        run: cd tests

      - name:
        run: cmake ..

      - name:
        run: make tests
