name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 
        run: cd msd

      - name: 
        run: mkdir -p build

      - name: 
        run: cd build

      - name:  
        run: cmake ..

      - name: 
        run: make

      - name:
        run: ./test-dmp

      - name:
        run: cd ..; rm -r build
